# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-27 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=100)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=256)),
                ('img', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=1)),
                ('token', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'axf_user',
            },
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(),
        ),
    ]
