# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-28 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='isselect',
            field=models.BooleanField(default=False),
        ),
    ]
